name: covid_hotspots
description: A COVID tracking app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fl_chart: ^0.12.0
  geocoding: ^1.0.5
  geolocator: ^6.0.0
  google_fonts: ^1.1.1
  http: ^0.12.2
  provider: ^4.3.2+2
  us_states: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Add assets here
  assets:
    - assets/images/
  # Fonts example
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
